name: Deploy Website

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/resamvi/resamvi.io-svelte:latest
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      env:
        USER: ${{ github.actor }}
        TOKEN: ${{ github.token }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        envs: USER,TOKEN
        script: |
          echo $TOKEN | docker login -u $USER --password-stdin ghcr.io
          docker pull ghcr.io/resamvi/resamvi.io-svelte:latest
          docker container rm -f resamvi-io
          docker run -d -p 127.0.0.1:3000:3000 --name resamvi-io ghcr.io/resamvi/resamvi.io-svelte:latest
