name: Deploy Website

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            git clone git@github.com:ResamVi/resamvi.io-svelte.git repo
            docker-compose -p resamvi.io -f repo/docker-compose.yml down
            docker-compose -p resamvi.io -f repo/docker-compose.yml up --detach --build --force-recreate
            rm -rf repo
